### ISSUE TITLE
Issues with the running of Downsteam.py 

### ISSUE THREAD

**Issue by cxliangUT** [ChangwenXu98/TransPolymer#13]
Hello, I successfully prepared the environment, and the pre-training goes pretty well, however, when I begin to run the Downstream file, I encountered this issue (attched in the output.txt). 

[output.txt](https://github.com/ChangwenXu98/TransPolymer/files/13665163/output.txt)

There could be some issues with line 364 of the code: 
train_data.iloc[:, 1] = scaler.fit_transform(train_data.iloc[:, 1].values.reshape(-1, 1))

I output the shape of the train_data and test_data, it is (2,1)

**Comment by ChangwenXu98** [comment]
Hi @cxliangUT, sorry for late reply. there are two columns in the input file, but the shape of train data and test data turns out to be 1-column. Have you modified the code about reading csv files? And is it possible that the files in your repo are incomplete?
