### ISSUE TITLE
OSError: Can't load tokenizer for 'roberta-base'.

### ISSUE THREAD

**Issue by veraLiuWL** [ChangwenXu98/TransPolymer#15]
I always get the following error when I run the .py file. Can you please help me to solve this problem?

Some weights of RobertaModel were not initialized from the model checkpoint at ckpt/pretrain.pt and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Traceback (most recent call last):
  File "/home/liwei/下载/TransPolymer-master/Attention_vis.py", line 137, in &lt;module&gt;
    tokenizer = PolymerSmilesTokenizer.from_pretrained("roberta-base", max_len=attention_config['blocksize'])
  File "/home/liwei/anaconda3/envs/TransPolymer/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 2013, in from_pretrained
    raise EnvironmentError(
OSError: Can't load tokenizer for 'roberta-base'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'roberta-base' is the correct path to a directory containing all relevant files for a PolymerSmilesTokenizer tokenizer.

**Comment by ChangwenXu98** [comment]
Hi, I think probably you have a local directory 'roberta-base'. Basically, we initialize the tokenizer by loading the pretrained roberta-base tokenizer while the regular expression used for tokenization has been adapted for smiles (that is the only difference between PolymerSmilesTokenizer and the normal roberta-base tokenizer). Let me know if you still encounter the error.
