### ISSUE TITLE
Smiles Tokenization for Pretraining

### ISSUE THREAD

**Issue by liberty-1776** [ChangwenXu98/TransPolymer#4]
```
class LoadPretrainData(Dataset):

    def __init__(self, tokenizer, dataset, blocksize):
        self.tokenizer = tokenizer
        self.blocksize = blocksize
        self.dataset = dataset

    def __len__(self):
        self.len = len(self.dataset)
        return self.len

    def __getitem__(self, i):
        smiles = self.dataset[i] #original
        **# smiles = self.dataset[i][0] updated version**

        encoding = self.tokenizer(
            str(smiles),
            add_special_tokens=True,
            max_length=self.blocksize,
            return_token_type_ids=False,
            padding="max_length",
            truncation=True,
            return_attention_mask=True,
            return_tensors='pt',
        )

        return dict(
            input_ids=encoding["input_ids"].flatten(),
            attention_mask=encoding["attention_mask"].flatten(),
        )
```

This is a code snippet from Dataset.py module.
I believe you have made a small mistake, when you try to access smiles from the dataset using self.dataset[i], you not only get the smile but '[' and ']' these symbols as well because it return the whole numpy array not the string.

For e.g SMILE = *NC(=O)c1ccc(C(=O)OCCCCCCCCCCCc2ccc(*)cc2)cc1
dataset[i] for some this smile will return something like array(['*NC(=O)c1ccc(C(=O)OCCCCCCCCCCCc2ccc(*)cc2)cc1'], dtype=object)
and when you will convert it into string inside encoding it will look like something [****'['****, '*', 'N', 'C', '(', '=', 'O', ')', 'c', '1', 'c', 'c', 'c', '(', 'C', '(', '=', 'O', ')', 'O', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'c', '2', 'c', 'c', 'c', '(', '*', ')', 'c', 'c', '2', ')', 'c', 'c', '1', ****']'****]. So basically you are feeding this to encoder instead of ['*', 'N', 'C', '(', '=', 'O', ')', 'c', '1', 'c', 'c', 'c', '(', 'C', '(', '=', 'O', ')', 'O', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'c', '2', 'c', 'c', 'c', '(', '*', ')', 'c', 'c', '2', ')', 'c', 'c', '1'], which _might_ improve the performance of the model.
To resolve that issue, only thing you need to do is just access the 1st index of the numpy array which I have added as a comment in the above code snippet.

**Comment by ChangwenXu98** [comment]
Hi @liberty-1776, thanks for raising the issue. Your suggestion is valuable, and we've updated the code. Meanwhile, even though the square brackets are included, the effect is just having a '[' after the start token '<s>' and a ']' before the end token '</s>', so we believe that the performance of the pretrained model will be almost the same after removing the square brackets. And the downstream performance should be the same as the results we report in paper (if not better) since the tokens from the downstream sequences do not have such issue.

**Comment by liberty-1776** [comment]
Yeah, that's right
