### ISSUE TITLE
Cloning Issue

### ISSUE THREAD

**Issue by TatemRios** [ChangwenXu98/TransPolymer#5]
Downloading ckpt/pretrain.pt/pytorch_model.bin (329 MB)
Error downloading object: ckpt/pretrain.pt/pytorch_model.bin (5e93519): Smudge error: Error downloading ckpt/pretrain.pt/pytorch_model.bin (5e93519a38a9f3ab51477591daf9ab443f5bf6a0c1bbfe6b5f5a5609fc95e767): batch response: **This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.**

Errors logged to /home/trios/TransPolymer/.git/lfs/logs/20230717T142851.171781074.log
Use `git lfs logs last` to view the log.
error: external filter 'git-lfs filter-process' failed
fatal: ckpt/pretrain.pt/pytorch_model.bin: smudge filter lfs failed
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

**Comment by ChangwenXu98** [comment]
Hi @TatemRios, thanks for raising the issue. The problem here is exactly the description in the error information: "This repository is over its data quota." Now the issue is solved, and you can do the following to clone the repository with Git LFS:
```
$ sudo apt-get install git-lfs
$ git lfs install
$ git lfs clone https://github.com/ChangwenXu98/TransPolymer.git
```
Let me know if you have any other question.
