### ISSUE TITLE
TypeError when using Downstream.py

### ISSUE THREAD

**Issue by wuyuhui-zju** [ChangwenXu98/TransPolymer#9]
```python
Traceback (most recent call last):
  File "D:\project\file\TransPolymer\test.py", line 4, in <module>
    tokenizer = PolymerSmilesTokenizer.from_pretrained("roberta-base", max_len=411)
  File "D:\anaconda3\envs\TransPolymer\lib\site-packages\transformers\tokenization_utils_base.py", line 1783, in from_pretrained
    return cls._from_pretrained(
  File "D:\anaconda3\envs\TransPolymer\lib\site-packages\transformers\tokenization_utils_base.py", line 1928, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "D:\project\file\TransPolymer\PolymerSmilesTokenization.py", line 216, in __init__
    with open(merges_file, encoding="utf-8") as merges_handle:
TypeError: expected str, bytes or os.PathLike object, not NoneType
``` 

I found the BUG on both windows and Ubuntu22.04.

**Comment by ChangwenXu98** [comment]
Hi, I never ran into this bug before. It seems that the bug takes place when you use the pretrained tokenizer. Could you share what's your `test.py` file? And can you check whether the version of the transformers package is `4.20.1` or not? And another suggestion is to replace the `PolymerSmilesTokenizer` with `RobertaTokenizer` and see whether you still encounter this problem.

**Comment by wuyuhui-zju** [comment]
Hello, I have solved the above problem by re-git clone. Besides, I would like to compare the performance of TransPolymer with that of a neural network trained with Polymer Genome (PG). I looked for the previous relevant literature, but did not find the calculation code of PG. May I ask how you reproduced the Polymer Genome? Thank you!

**Comment by wuyuhui-zju** [comment]
I find this github repository: https://github.com/Ramprasad-Group/multi-task-learning/tree/main in SI. But there doesn't seem to be a PG calculation script in it

**Comment by ChangwenXu98** [comment]
I once considered reproducing the results by PG myself, but I found that the authors didn't open-source their code. Maybe you can directly reach out to Ramprasad for the source code.
